const mongoose = require('mongoose');

const MenteeSchema = new mongoose.Schema({
  name: { type: String, required: true },
  year: { type: String, required: true },
  registrationNumber: { type: String, required: true, unique: true },
  email: { type: String, required: true, unique: true },
  role: { type: String, default: 'mentee' },
  password: { type: String, required: true },
  mentor: { type: mongoose.Schema.Types.ObjectId, ref: 'Mentor' }, // Reference to Mentor
  photoLink: { type: String }, // Add this line
  phone :{ type:Number },
  class1: {type : String , required: true},
  FatherName: { type: String },
  MotherName: { type: String },
  PlaceOfBirth: { type: String },
  Gender: { type: String, enum: ['Male', 'Female', 'Other'], required: true },
  DOB: { type: Date, required: true },
  Nationality: { type: String },
  Religion: { type: String },
  MaritalStatus: { type: String },
  BloodGroup: { type: String },
  Caste: { type: String },
  CasteName: { type: String },
  JoinType: { type: String },
  DOJ: { type: Date },
  DOR: { type: Date },
  RelieveType: { type: String },
  RelieveReason: { type: String },
  IsPH: { type: Boolean },
  PHType: { type: String },
  IsLateral: { type: Boolean },
  ReserveCategory: { type: String },
  UIDNo: { type: String },
  UIDEnrollNo: { type: String },
  IsLocal: { type: Boolean },
  IsEBC: { type: Boolean },
  IsMinority: { type: Boolean },
  ParentIncome: { type: Number },
  Mark1: { type: String},
  Mark2: { type: String },
  classesAttended: { type: Number },
  totalClasses: { type: Number },
  sem1Gpa: { type: Number },
  sem2Gpa: { type: Number },
  sem3Gpa: { type: Number },
  sem4Gpa: { type: Number },
  sem5Gpa: { type: Number },
  sem6Gpa: { type: Number },
  sem7Gpa: { type: Number },
  sem8Gpa: { type: Number }
});

module.exports = mongoose.model('Mentee', MenteeSchema);